### ISSUE TITLE
is a mok ?

### ISSUE THREAD

**Issue by jmvizcainoio** [ealexhaywood/gitlab-alerts#1]
Hi,

i can see inside the code server.js that say

/ Do stuff with alerts

Have you got a final version ?

Thanks

**Comment by ealexhaywood** [comment]
Hi :)  

I don't have a final version yet, but I plan to do a release in March or April.  I have been busy with other work, but this is definitely on the roadmap!

**Comment by ealexhaywood** [comment]
Hi @jmvizcainoio, I have a very, very early workable version of the app working now.  It doesn't offer much in terms of customization but it will POST to GitLab now to autogenerate issues.
